framework:
    secret: '%env(APP_SECRET)%'
    validation: { enable_annotations: true }
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    #esi: true
    #fragments: true
    php_errors:
        log: true

    templating:
        engines:
            - twig
