controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /api

client_controllers:
    resource: ../../src/Controller/Client/
    type: annotation
    prefix: /api/client

admin_controllers:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: /api/admin

admin_accounts_controllers:
    resource: ../../src/Controller/Admin/Account
    type: annotation
    prefix: /api/admin/account

company_controllers:
    resource: ../../src/Controller/Company/
    type: annotation
    prefix: /api/company

analytics_controllers:
    resource: ../../src/Controller/Analytics/
    type: annotation
    prefix: /api/analytics