controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /api

client_controllers:
    resource: ../../src/Controller/Client/
    type: annotation
    prefix: /api/client

admin_controllers:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: /api/admin